UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='500';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='H' WHERE PROGRAM_REQUIREMENT_CODE='501';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='C' WHERE PROGRAM_REQUIREMENT_CODE='502';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='D' WHERE PROGRAM_REQUIREMENT_CODE='503';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='D' WHERE PROGRAM_REQUIREMENT_CODE='505';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='c' WHERE PROGRAM_REQUIREMENT_CODE='506';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='T' WHERE PROGRAM_REQUIREMENT_CODE='507';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='740';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='741';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='C' WHERE PROGRAM_REQUIREMENT_CODE='742';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='H' WHERE PROGRAM_REQUIREMENT_CODE='743';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='I' WHERE PROGRAM_REQUIREMENT_CODE='744';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='J' WHERE PROGRAM_REQUIREMENT_CODE='745';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='F' WHERE PROGRAM_REQUIREMENT_CODE='746';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='D' WHERE PROGRAM_REQUIREMENT_CODE='747';

