UPDATE OPTIONAL_PROGRAM SET LABEL = 'French Immersion'  WHERE OPTIONAL_PROGRAM_CODE='FI';
UPDATE OPTIONAL_PROGRAM SET LABEL = 'Advanced Placement'  WHERE OPTIONAL_PROGRAM_CODE='AD';
UPDATE OPTIONAL_PROGRAM SET LABEL = 'International Baccalaureate as a Certificate'  WHERE OPTIONAL_PROGRAM_CODE='BC';
UPDATE OPTIONAL_PROGRAM SET LABEL = 'International Baccalaureate as a Diploma'  WHERE OPTIONAL_PROGRAM_CODE='BD';
UPDATE OPTIONAL_PROGRAM SET LABEL = 'Career Program'  WHERE OPTIONAL_PROGRAM_CODE='CP';
UPDATE OPTIONAL_PROGRAM SET LABEL = 'Dual Dogwood' WHERE OPTIONAL_PROGRAM_CODE='DD';