UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='500' WHERE PROGRAM_REQUIREMENT_CODE='500';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='501' WHERE PROGRAM_REQUIREMENT_CODE='501';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='502' WHERE PROGRAM_REQUIREMENT_CODE='502';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='503' WHERE PROGRAM_REQUIREMENT_CODE='503';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='504' WHERE PROGRAM_REQUIREMENT_CODE='504';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='505' WHERE PROGRAM_REQUIREMENT_CODE='505';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='506' WHERE PROGRAM_REQUIREMENT_CODE='506';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='507' WHERE PROGRAM_REQUIREMENT_CODE='507';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='740' WHERE PROGRAM_REQUIREMENT_CODE='740';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='741' WHERE PROGRAM_REQUIREMENT_CODE='741';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='742' WHERE PROGRAM_REQUIREMENT_CODE='742';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='743' WHERE PROGRAM_REQUIREMENT_CODE='743';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='744' WHERE PROGRAM_REQUIREMENT_CODE='744';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='745' WHERE PROGRAM_REQUIREMENT_CODE='745';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='746' WHERE PROGRAM_REQUIREMENT_CODE='746';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='747' WHERE PROGRAM_REQUIREMENT_CODE='747';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='748' WHERE PROGRAM_REQUIREMENT_CODE='748';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='720' WHERE PROGRAM_REQUIREMENT_CODE='720';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='721';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='722';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='723';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='4' WHERE PROGRAM_REQUIREMENT_CODE='724';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='5' WHERE PROGRAM_REQUIREMENT_CODE='725';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='8' WHERE PROGRAM_REQUIREMENT_CODE='726';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='9' WHERE PROGRAM_REQUIREMENT_CODE='727';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='6' WHERE PROGRAM_REQUIREMENT_CODE='728';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='7' WHERE PROGRAM_REQUIREMENT_CODE='729';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='730' WHERE PROGRAM_REQUIREMENT_CODE='730';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='731' WHERE PROGRAM_REQUIREMENT_CODE='731';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='10' WHERE PROGRAM_REQUIREMENT_CODE='732';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='818';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='819';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='820' WHERE PROGRAM_REQUIREMENT_CODE='820';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='700' WHERE PROGRAM_REQUIREMENT_CODE='700';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='701';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='702';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='703';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='4' WHERE PROGRAM_REQUIREMENT_CODE='704';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='5' WHERE PROGRAM_REQUIREMENT_CODE='705';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='6' WHERE PROGRAM_REQUIREMENT_CODE='706';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='7' WHERE PROGRAM_REQUIREMENT_CODE='707';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='8' WHERE PROGRAM_REQUIREMENT_CODE='708';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='9' WHERE PROGRAM_REQUIREMENT_CODE='709';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='10' WHERE PROGRAM_REQUIREMENT_CODE='710';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='11' WHERE PROGRAM_REQUIREMENT_CODE='711';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='12' WHERE PROGRAM_REQUIREMENT_CODE='712';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='13' WHERE PROGRAM_REQUIREMENT_CODE='713';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='15' WHERE PROGRAM_REQUIREMENT_CODE='714';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='815';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='816';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='817';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='100' WHERE PROGRAM_REQUIREMENT_CODE='100';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='101';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='102';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='103';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='4' WHERE PROGRAM_REQUIREMENT_CODE='104';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='5' WHERE PROGRAM_REQUIREMENT_CODE='105';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='6' WHERE PROGRAM_REQUIREMENT_CODE='106';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='7' WHERE PROGRAM_REQUIREMENT_CODE='107';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='8' WHERE PROGRAM_REQUIREMENT_CODE='108';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='9' WHERE PROGRAM_REQUIREMENT_CODE='109';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='10' WHERE PROGRAM_REQUIREMENT_CODE='110';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='11' WHERE PROGRAM_REQUIREMENT_CODE='111';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='12' WHERE PROGRAM_REQUIREMENT_CODE='112';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='13' WHERE PROGRAM_REQUIREMENT_CODE='113';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='15' WHERE PROGRAM_REQUIREMENT_CODE='115';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='16' WHERE PROGRAM_REQUIREMENT_CODE='116';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='17' WHERE PROGRAM_REQUIREMENT_CODE='117';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='18' WHERE PROGRAM_REQUIREMENT_CODE='118';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='300';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='301';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='302';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='15' WHERE PROGRAM_REQUIREMENT_CODE='303';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='18' WHERE PROGRAM_REQUIREMENT_CODE='304';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='675' WHERE PROGRAM_REQUIREMENT_CODE='675';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='650' WHERE PROGRAM_REQUIREMENT_CODE='650';








