UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='504';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='506';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='507';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='650';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='700';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='675';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='747';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='740';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='741';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='742';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='743';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='744';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='745';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='746';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='720';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='730';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER=NULL WHERE PROGRAM_REQUIREMENT_CODE='820';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='19' WHERE PROGRAM_REQUIREMENT_CODE='100';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='1' WHERE PROGRAM_REQUIREMENT_CODE='500';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='2' WHERE PROGRAM_REQUIREMENT_CODE='501';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='3' WHERE PROGRAM_REQUIREMENT_CODE='502';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='4' WHERE PROGRAM_REQUIREMENT_CODE='503';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_NUMBER='4' WHERE PROGRAM_REQUIREMENT_CODE='505';