-- OPTIONAL_PROGRAM_REQUIREMENT definition

CREATE TABLE "OPTIONAL_PROGRAM_REQUIREMENT" 
   (  "OPTIONAL_PROGRAM_RQMT_ID" RAW(16) DEFAULT SYS_GUID(), 
	"OPTIONAL_PROGRAM_ID" RAW(16) NOT NULL ENABLE,
	"OPTIONAL_PROGRAM_RQMT_CODE" VARCHAR2(4) NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
   CONSTRAINT "OPTIONAL_PROGRAM_REQUIREMENT_PK" PRIMARY KEY ("OPTIONAL_PROGRAM_RQMT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE, 
   CONSTRAINT "OPT_PGMRQMT_OPT_PGM_RQMTCD_FK" FOREIGN KEY ("OPTIONAL_PROGRAM_RQMT_CODE")
    REFERENCES "OPTIONAL_PROGRAM_RQMT_CODE" ("OPTIONAL_PROGRAM_RQMT_CODE") ENABLE, 
   CONSTRAINT "OPT_PGMRQMT_OPT_PGMID_FK" FOREIGN KEY ("OPTIONAL_PROGRAM_ID")
    REFERENCES "OPTIONAL_PROGRAM" ("OPTIONAL_PROGRAM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
