DELETE FROM PROGRAM_REQUIREMENT WHERE GRADUATION_PROGRAM_CODE = '1950' AND PROGRAM_REQUIREMENT_CODE = '507';

DELETE FROM PROGRAM_REQUIREMENT_CODE WHERE PROGRAM_REQUIREMENT_CODE='507';

DELETE FROM REQUIREMENT_TYPE_CODE WHERE REQUIREMENT_TYPE_CODE='MAC19';

INSERT INTO REQUIREMENT_TYPE_CODE (REQUIREMENT_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE) 
VALUES('MAC', 'Min Adult Courses', 'Algorithm identifies student courses taken after starting the program. Currently applies to the Adult Graduation Diploma Program only.', 60, TIMESTAMP '2021-08-12 00:00:00.000000');

UPDATE PROGRAM_REQUIREMENT_CODE
SET LABEL='3 Courses completed after starting the program',
	DESCRIPTION='Students must complete three of five required courses after starting the program',
	NOT_MET_DESC='Fewer than 3 eligible courses completed after starting the program',
	REQUIREMENT_TYPE_CODE='MAC'
WHERE PROGRAM_REQUIREMENT_CODE='504';

DELETE FROM REQUIREMENT_TYPE_CODE WHERE REQUIREMENT_TYPE_CODE='MAC18';