UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='D' WHERE PROGRAM_REQUIREMENT_CODE='747';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='R' WHERE PROGRAM_REQUIREMENT_CODE='720';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='721';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='722';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='C' WHERE PROGRAM_REQUIREMENT_CODE='723';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='H' WHERE PROGRAM_REQUIREMENT_CODE='724';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='I' WHERE PROGRAM_REQUIREMENT_CODE='725';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='N' WHERE PROGRAM_REQUIREMENT_CODE='726';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='O' WHERE PROGRAM_REQUIREMENT_CODE='727';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='P' WHERE PROGRAM_REQUIREMENT_CODE='728';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='Q' WHERE PROGRAM_REQUIREMENT_CODE='729';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='S' WHERE PROGRAM_REQUIREMENT_CODE='730';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='818';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='819';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='g' WHERE PROGRAM_REQUIREMENT_CODE='700';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='r' WHERE PROGRAM_REQUIREMENT_CODE='701';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='702';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='703';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='a' WHERE PROGRAM_REQUIREMENT_CODE='704';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='C' WHERE PROGRAM_REQUIREMENT_CODE='705';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='b' WHERE PROGRAM_REQUIREMENT_CODE='706';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='H' WHERE PROGRAM_REQUIREMENT_CODE='707';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='t' WHERE PROGRAM_REQUIREMENT_CODE='708';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='I' WHERE PROGRAM_REQUIREMENT_CODE='709';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='V' WHERE PROGRAM_REQUIREMENT_CODE='710';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='I' WHERE PROGRAM_REQUIREMENT_CODE='711';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='U' WHERE PROGRAM_REQUIREMENT_CODE='712';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='W' WHERE PROGRAM_REQUIREMENT_CODE='713';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='i' WHERE PROGRAM_REQUIREMENT_CODE='714';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='r' WHERE PROGRAM_REQUIREMENT_CODE='815';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='816';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='817';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='g' WHERE PROGRAM_REQUIREMENT_CODE='100';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='r' WHERE PROGRAM_REQUIREMENT_CODE='101';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='102';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='103';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='a' WHERE PROGRAM_REQUIREMENT_CODE='104';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='h' WHERE PROGRAM_REQUIREMENT_CODE='105';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='b' WHERE PROGRAM_REQUIREMENT_CODE='106';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='H' WHERE PROGRAM_REQUIREMENT_CODE='107';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='t' WHERE PROGRAM_REQUIREMENT_CODE='108';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='I' WHERE PROGRAM_REQUIREMENT_CODE='109';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='j' WHERE PROGRAM_REQUIREMENT_CODE='110';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='k' WHERE PROGRAM_REQUIREMENT_CODE='111';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='m' WHERE PROGRAM_REQUIREMENT_CODE='112';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='n' WHERE PROGRAM_REQUIREMENT_CODE='113';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='p' WHERE PROGRAM_REQUIREMENT_CODE='115';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='o' WHERE PROGRAM_REQUIREMENT_CODE='116';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='i' WHERE PROGRAM_REQUIREMENT_CODE='117';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='q' WHERE PROGRAM_REQUIREMENT_CODE='118';

UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='B' WHERE PROGRAM_REQUIREMENT_CODE='300';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='A' WHERE PROGRAM_REQUIREMENT_CODE='301';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='r' WHERE PROGRAM_REQUIREMENT_CODE='302';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='p' WHERE PROGRAM_REQUIREMENT_CODE='303';
UPDATE PROGRAM_REQUIREMENT_CODE SET TRAX_REQ_CHAR='q' WHERE PROGRAM_REQUIREMENT_CODE='304';









