GRANT SELECT ON GRADUATION_PROGRAM_CODE TO GRAD_READONLY;
GRANT SELECT ON REQUIREMENT_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON OPTIONAL_PROGRAM TO GRAD_READONLY;
GRANT SELECT ON OPTIONAL_PROGRAM_RQMT_CODE TO GRAD_READONLY;
GRANT SELECT ON PROGRAM_REQUIREMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON OPTIONAL_PROGRAM_REQUIREMENT TO GRAD_READONLY;
GRANT SELECT ON PROGRAM_REQUIREMENT TO GRAD_READONLY;
