UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='12 credits - French Language', DESCRIPTION='Students must complete a minimum of twelve additional credits in French', NOT_MET_DESC='Fewer than 12 credits - French Language'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='204';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='4 Gr 11 or 12 credits - French Language', DESCRIPTION='Of the twelve additional credits in French, a minimum of four credits must be at the Grade 11 or 12 level', NOT_MET_DESC='Fewer than 4 Gr 11 or 12 credits - French Language'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='205';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Literacy 10 Assessment', DESCRIPTION='Student must have written the Literacy 10 Assessment in English', NOT_MET_DESC='No Literacy 10 Assessment - English'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='403';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Literacy 12 Assessment', DESCRIPTION='Student must have written the Literacy 12 Assessment in English', NOT_MET_DESC='No Literacy 12 Assessment - English'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='404';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Français langue seconde-immersion 11', DESCRIPTION='4-credit course must be completed in Français langue seconde-immersion 11', NOT_MET_DESC='No Français langue seconde-immersion 11'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='916';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='4 credits - French language', DESCRIPTION='Students must complete a course (min 4-credits) in French at the grade 11 or 12 level', NOT_MET_DESC='No French language course at the grade 11 or 12 level'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='917';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Advanced Placement participation', DESCRIPTION='A school must report the student as participating in the Advanced Placement program', NOT_MET_DESC='Not Reported by School'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='951';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Career Program participation', DESCRIPTION='The school must report the student as participating in a Career Program', NOT_MET_DESC='Not Reported by School'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='954';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Student graduating on the 1996 Programme Francophone receives an English dual dogwood automatically', DESCRIPTION='Student enrolled in Programme Francophone must complete their main program, and then will also receive their English Dogwood', NOT_MET_DESC='Student has not yet completed their main program'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='955';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='A student''s Main Program is SCCP and they are being reported by a Programme francophone school (SD 093).', DESCRIPTION='Student must be on SCCP program and reported by a Programme francophone school to also receive a French Language SCCP certificate. Else, ticket is required to create a French Language SCCP certificate.', NOT_MET_DESC='Not Reported by School'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='956';

UPDATE OPTIONAL_PROGRAM_RQMT_CODE
SET LABEL='Student graduating on the 1986 Programme Francophone receives an English dual dogwood automatically', DESCRIPTION='Student enrolled in Programme Francophone must complete their main program, and then will also receive their English Dogwood', NOT_MET_DESC='Student has not yet completed their main program'
WHERE OPTIONAL_PROGRAM_RQMT_CODE='958';

INSERT INTO OPTIONAL_PROGRAM_RQMT_CODE
(OPTIONAL_PROGRAM_RQMT_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, ACTIVE_REQUIREMENT, LANGUAGE_OF_INSTRUCTION, NOT_MET_DESC, REQUIRED_CREDITS, REQUIRED_LEVEL, REQUIREMENT_CATEGORY, REQUIREMENT_TYPE_CODE, TRAX_REQ_NUMBER, TRAX_REQ_CHAR)
VALUES('959', 'Student has completed their main program', 'An SCCP student cannot be issued a French language certificates until a program completion date has been sent in by the school', 320, 'Y', NULL, 'Student has no completion date submitted by the school or completion date is still a future date.', NULL, NULL, NULL, 'SR', '959', NULL);


INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE61958FB51E0539AE9228E7AF3', 'F16B2E535D77C7EBE0539AE9228E1A73', '951');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE61959FB51E0539AE9228E7AF3', 'F16B2E535D78C7EBE0539AE9228E1A73', '952');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195AFB51E0539AE9228E7AF3', 'F16B2E535D79C7EBE0539AE9228E1A73', '953');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195BFB51E0539AE9228E7AF3', 'F16B2E535D7AC7EBE0539AE9228E1A73', '954');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195CFB51E0539AE9228E7AF3', 'F16B2E535D77C7EBE0539AE9228E1A73', '957');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195DFB51E0539AE9228E7AF3', 'F16B2E535D78C7EBE0539AE9228E1A73', '957');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195EFB51E0539AE9228E7AF3', 'F16B2E535D79C7EBE0539AE9228E1A73', '957');
INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F4350FE6195FFB51E0539AE9228E7AF3', 'F16B2E535D7AC7EBE0539AE9228E1A73', '957');


INSERT INTO OPTIONAL_PROGRAM_REQUIREMENT (OPTIONAL_PROGRAM_RQMT_ID, OPTIONAL_PROGRAM_ID, OPTIONAL_PROGRAM_RQMT_CODE) VALUES('F43E436F7B463352E0539AE9228E5683', 'CED2362BDA8B7A33E0539AE9228E79B6', '959');

DELETE FROM OPTIONAL_PROGRAM_REQUIREMENT WHERE OPTIONAL_PROGRAM_ID = 'CED2362BDA8B7A33E0539AE9228E79B6' AND OPTIONAL_PROGRAM_RQMT_CODE = '957';

