UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XA' AND LABEL = 'Business and Applied Business';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XB'; AND LABEL = 'Fine Arts, Design and Media';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XC' AND LABEL = 'Fitness and Recreation';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XD' AND LABEL = 'Health and Human Services';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XE' AND LABEL = 'Liberal Arts and Humanities';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XF' AND LABEL = 'Science and Applied Science';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XG' AND LABEL = 'Tourism, Hospitality and Foods';

UPDATE CAREER_PROGRAM_CODE
SET EFFECTIVE_DATE=TIMESTAMP'2006-09-01  00:00:00.0'
WHERE CAREER_PROGRAM_CODE = 'XH' AND LABEL = 'Trades and Technology';