UPDATE GRADUATION_PROGRAM_CODE SET LABEL = 'Graduation Program 2018' WHERE GRADUATION_PROGRAM_CODE='2018-PF';
UPDATE GRADUATION_PROGRAM_CODE SET LABEL = 'Graduation Program 2004' WHERE GRADUATION_PROGRAM_CODE='2004-PF';
UPDATE GRADUATION_PROGRAM_CODE SET LABEL = 'Graduation Program 1995' WHERE GRADUATION_PROGRAM_CODE='1996-PF';