UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 2018 B.C. Certificate of Graduation or “Dogwood Diploma” program' WHERE GRADUATION_PROGRAM_CODE='2018-EN';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 2018 Diplôme de fin d''études secondaires en Colombie-Britannique program' WHERE GRADUATION_PROGRAM_CODE='2018-PF';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 2004 B.C. Certificate of Graduation or “Dogwood Diploma” program' WHERE GRADUATION_PROGRAM_CODE='2004-EN';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 2004 Diplôme de fin d''études secondaires en Colombie-Britannique' WHERE GRADUATION_PROGRAM_CODE='2004-PF';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 1995 B.C. Certificate of Graduation or “Dogwood Diploma” program' WHERE GRADUATION_PROGRAM_CODE='1996-EN';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 1995 Diplôme de fin d''études secondaires en Colombie-Britannique' WHERE GRADUATION_PROGRAM_CODE='1996-PF';
UPDATE GRADUATION_PROGRAM_CODE SET DESCRIPTION = 'The 1986 B.C. Certificate of Graduation or “Dogwood Diploma” program' WHERE GRADUATION_PROGRAM_CODE='1986-EN';
