package ca.bc.gov.educ.api.program.util;

public class PermissionsContants {
	
	private PermissionsContants() {}
	
	public static final String PREFIX = "#oauth2.hasAnyScope('";
	public static final String SUFFIX = "')";

	public static final String READ_GRAD_PROGRAM = PREFIX + "READ_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String CREATE_GRAD_PROGRAM = PREFIX + "CREATE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String UPDATE_GRAD_PROGRAM = PREFIX + "UPDATE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String DELETE_GRAD_PROGRAM = PREFIX + "DELETE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String READ_GRAD_PROGRAM_RULES = PREFIX + "READ_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String CREATE_GRAD_PROGRAM_RULES = PREFIX + "CREATE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String UPDATE_GRAD_PROGRAM_RULES = PREFIX + "UPDATE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String DELETE_GRAD_PROGRAM_RULES = PREFIX + "DELETE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String READ_GRAD_OPTIONAL_PROGRAM = PREFIX + "READ_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String CREATE_GRAD_OPTIONAL_PROGRAM = PREFIX + "CREATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String UPDATE_GRAD_OPTIONAL_PROGRAM = PREFIX + "UPDATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String DELETE_GRAD_OPTIONAL_PROGRAM = PREFIX + "DELETE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	public static final String READ_GRAD_OPTIONAL_PROGRAM_RULES = PREFIX + "READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String CREATE_GRAD_OPTIONAL_PROGRAM_RULES = PREFIX + "CREATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String UPDATE_GRAD_OPTIONAL_PROGRAM_RULES = PREFIX + "UPDATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String DELETE_GRAD_OPTIONAL_PROGRAM_RULES = PREFIX + "DELETE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String READ_ALGORITHM_DATA = PREFIX + "READ_GRAD_PROGRAM_RULES_DATA', 'READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	public static final String READ_GRAD_CAREER_PROGRAM = PREFIX + "READ_GRAD_CAREER_PROGRAM_CODE_DATA"+ SUFFIX;
	public static final String CREATE_REQUIREMENT_TYPE = PREFIX + "CREATE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ SUFFIX;
	public static final String UPDATE_REQUIREMENT_TYPE = PREFIX + "UPDATE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ SUFFIX;
	public static final String DELETE_REQUIREMENT_TYPE = PREFIX + "DELETE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ SUFFIX;
	public static final String READ_GRAD_REQUIREMENT_TYPE_CODE = PREFIX + "READ_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ SUFFIX;
}
