package ca.bc.gov.educ.api.program.util;

public interface PermissionsContants {
	String _PREFIX = "#oauth2.hasAnyScope('";
	String _SUFFIX = "')";

	String READ_GRAD_PROGRAM = _PREFIX + "READ_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String CREATE_GRAD_PROGRAM = _PREFIX + "CREATE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String UPDATE_GRAD_PROGRAM = _PREFIX + "UPDATE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String DELETE_GRAD_PROGRAM = _PREFIX + "DELETE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String READ_GRAD_PROGRAM_RULES = _PREFIX + "READ_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String CREATE_GRAD_PROGRAM_RULES = _PREFIX + "CREATE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String UPDATE_GRAD_PROGRAM_RULES = _PREFIX + "UPDATE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String DELETE_GRAD_PROGRAM_RULES = _PREFIX + "DELETE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_GRAD_OPTIONAL_PROGRAM = _PREFIX + "READ_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String CREATE_GRAD_OPTIONAL_PROGRAM = _PREFIX + "CREATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String UPDATE_GRAD_OPTIONAL_PROGRAM = _PREFIX + "UPDATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String DELETE_GRAD_OPTIONAL_PROGRAM = _PREFIX + "DELETE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String READ_GRAD_OPTIONAL_PROGRAM_RULES = _PREFIX + "READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String CREATE_GRAD_OPTIONAL_PROGRAM_RULES = _PREFIX + "CREATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String UPDATE_GRAD_OPTIONAL_PROGRAM_RULES = _PREFIX + "UPDATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String DELETE_GRAD_OPTIONAL_PROGRAM_RULES = _PREFIX + "DELETE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_ALGORITHM_DATA = _PREFIX + "READ_GRAD_PROGRAM_RULES_DATA', 'READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_GRAD_CAREER_PROGRAM = _PREFIX + "READ_GRAD_CAREER_PROGRAM_CODE_DATA"+ _SUFFIX;
	String CREATE_REQUIREMENT_TYPE = _PREFIX + "CREATE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ _SUFFIX;
	String UPDATE_REQUIREMENT_TYPE = _PREFIX + "UPDATE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ _SUFFIX;
	String DELETE_REQUIREMENT_TYPE = _PREFIX + "DELETE_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ _SUFFIX;
	String READ_GRAD_REQUIREMENT_TYPE_CODE = _PREFIX + "READ_GRAD_REQUIREMENT_TYPE_CODE_DATA"+ _SUFFIX;
}
